# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stephanie Leroux
email: stephanie.leroux_x_univ-grenoble-alpes.fr
description: > # this means to ignore newlines until "baseurl:"
  webpage
baseurl: "" # the subpath of your site, e.g. /blog
url: http://stephanieleroux.github.io/
github_username:  stephanieleroux
header-img: img/home-bg.jpg

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
